### ISSUE TITLE
Tokenization fails with WiC

### ISSUE THREAD

**Issue by claravania** [jiant-dev/jiant#140]
**Describe the bug**
I got the following error when using `tokenize_and_cache.py` for processing WiC.

```
Traceback (most recent call last):
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 214, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 168, in main
    args=args,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 53, in chunk_and_save
    args=args,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 129, in iter_chunk_and_save
    recorder_callback=max_valid_length_recorder,
  File "/scratch/cv50/jiant-2/jiant/jiant/shared/caching.py", line 91, in iter_chunk_and_save
    for datum in data:
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/preprocessing.py", line 145, in iter_chunk_convert_examples_to_dataset
    verbose=verbose,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/preprocessing.py", line 216, in iter_chunk_tokenize_and_featurize
    yield example.tokenize(tokenizer).featurize(tokenizer, feat_spec)
  File "/scratch/cv50/jiant-2/jiant/jiant/tasks/lib/wic.py", line 36, in tokenize
    sentence=self.sentence1, span=self.span1, tokenizer=tokenizer,
  File "/scratch/cv50/jiant-2/jiant/jiant/tasks/lib/templates/hacky_tokenization_matching.py", line 118, in get_token_span
    assert starts_with(tokenized, tokenized_start1)
AssertionError
```

**To Reproduce**

```
python ${JIANT_PATH}/proj/main/tokenize_and_cache.py \
    		--task_config_path ${DATA_DIR}/configs/${TASK_NAME}_config.json \
    		--model_type ${MODEL_TYPE} \
    		--model_tokenizer_path ${MODELS_DIR}/${MODEL_TYPE}/tokenizer \
    		--phases train,val,test \
    		--max_seq_length 256 \
    		--do_iter \
    		--smart_truncate \
    		--output_dir ${CACHE_DIR}/${MODEL_TYPE}/${TASK_NAME}
```

1. Tell use which version of `jiant` you're using: jiant-2
2. Describe the environment where you're using `jiant`: 1 P40 GPU
3. MODEL_TYPE: `roberta-base`
4. TASK_NAME: `wic`

**Comment by jeswan** [comment]
@claravania I unable to reproduce this issue. Can you post the commit hash and the contents of `${DATA_DIR}/configs/${TASK_NAME}_config.json`?

**Comment by YianZhang** [comment]
I have the same issue. 
My config file:
```
{
  "task": "wic",
  "paths": {
    "train": "/scratch/work/js11133/public/task_data/WiC/train.jsonl",
    "val": "/scratch/work/js11133/public/task_data/WiC/val.jsonl",
    "test": "/scratch/work/js11133/public/task_data/WiC/test.jsonl"
  },
  "name": "wic"
}
```
I pulled the remote repo right before running this, so commithash = ab0a65e79ef636d2eb72a64d6df22dee8a5c7dc5.

I printed `tokenized` and `tokenized_start1`: `['Do', 'Ġyou', 'Ġwant', 'Ġto', 'Ġcome', 'Ġover', 'Ġto', 'Ġmy', 'Ġplace', 'Ġlater', '?'] ['Do', 'Ġyou', 'Ġwant', 'Ġto', 'Ġcome', 'Ġover', 'Ġto', 'Ġmy', 'Ġ']`. Hope this helps!

**Comment by jeswan** [comment]
I am now able to reproduce after updating to the `transformers` and `tokenizers` version used by the project.

**Comment by claravania** [comment]
Yes, just to confirm my config file is the same as @YianZhang.
