### ISSUE TITLE
Tokenization error for SciTail

### ISSUE THREAD

**Issue by claravania** [jiant-dev/jiant#188]
**Describe the bug**
I got the following error with `tokenize_and_cache.py` for SciTail:

```
SciTailTask
  [train]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/scitail/train.jsonl
  [val]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/scitail/val.jsonl
  [test]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/scitail/test.jsonl
Tokenizing:   0%|                                                                                | 0/23097 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 214, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 168, in main
    args=args,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 53, in chunk_and_save
    args=args,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 129, in iter_chunk_and_save
    recorder_callback=max_valid_length_recorder,
  File "/scratch/cv50/jiant-2/jiant/jiant/shared/caching.py", line 91, in iter_chunk_and_save
    for datum in data:
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/preprocessing.py", line 145, in iter_chunk_convert_examples_to_dataset
    verbose=verbose,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/preprocessing.py", line 216, in iter_chunk_tokenize_and_featurize
    yield example.tokenize(tokenizer).featurize(tokenizer, feat_spec)
  File "/scratch/cv50/jiant-2/jiant/jiant/tasks/lib/scitail.py", line 29, in tokenize
    input_hypothesis=tokenizer.tokenize(self.input_hypothesis),
  File "/scratch/cv50/packages/miniconda3/envs/jiant2/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 364, in tokenize
    tokenized_text = split_on_tokens(no_split_token, text)
  File "/scratch/cv50/packages/miniconda3/envs/jiant2/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 338, in split_on_tokens
    if not text.strip():
AttributeError: 'float' object has no attribute 'strip'
```

**To Reproduce**:
```
python ${JIANT_PATH}/proj/main/tokenize_and_cache.py \
    		--task_config_path ${DATA_DIR}/configs/${TASK_NAME}_config.json \
    		--model_type ${MODEL_NAME} \
    		--model_tokenizer_path ${MODELS_DIR}/${MODEL_NAME}/tokenizer \
    		--phases train,val,test \
    		--max_seq_length 256 \
    		--do_iter \
    		--smart_truncate \
    		--output_dir ${CACHE_DIR}/${MODEL_NAME}/${TASK_NAME}
```
1. Tell use which version of `jiant` you're using: jiant2 commit 75274759808dbc0ebe9cf4e538174ba574845f7c
2. Describe the environment where you're using `jiant`, e.g, "2 P40 GPUs": 1 P40 GPU
3. Provide the experiment config artifact (e.g., `defaults.conf`):
```
{
  "task": "scitail",
  "paths": {
    "train": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/scitail/train.jsonl",
    "val": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/scitail/val.jsonl",
    "test": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/scitail/test.jsonl"
  },
  "name": "scitail"
}
```
4. MODEL_TYPE: `roberta-base-100M-1`

**Comment by jeswan** [comment]
Closed with https://github.com/nyu-mll/jiant/pull/1123
