### ISSUE TITLE
Tokenization error for WSC

### ISSUE THREAD

**Issue by claravania** [jiant-dev/jiant#190]
**Describe the bug**
Tokenization error when loading training data:
```
WSCTask
  [train]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/wsc/train.jsonl
  [test]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/wsc/test.jsonl
  [val]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/wsc/val.jsonl
Traceback (most recent call last):
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 214, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 165, in main
    examples=task.get_train_examples(),
  File "/scratch/cv50/jiant-2/jiant/jiant/tasks/lib/wsc.py", line 160, in get_train_examples
    return self._create_examples(lines=read_json_lines(self.train_path), set_type="train")
  File "/scratch/cv50/jiant-2/jiant/jiant/tasks/lib/wsc.py", line 177, in _create_examples
    span1_idx=line["target"]["span1_index"],
KeyError: 'target'
```

**To Reproduce**
1. Tell use which version of `jiant` you're using: jiant2 commit 75274759808dbc0ebe9cf4e538174ba574845f7c
2. Describe the environment where you're using `jiant`, e.g, "2 P40 GPUs": 1 P40 GPU
3. Provide the experiment config artifact (e.g., `defaults.conf`)

Task config:
```
{
  "task": "wsc",
  "paths": {
    "train": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/wsc/train.jsonl",
    "test": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/wsc/test.jsonl",
    "val": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/wsc/val.jsonl"
  },
  "name": "wsc"
}
```

**Comment by jeswan** [comment]
Looks like the data format is slightly different in [`datasets`](https://github.com/huggingface/datasets). Will open a PR for a fix shortly.

**Comment by jeswan** [comment]
Closed with: https://github.com/nyu-mll/jiant/pull/1122

**Comment by jeswan** [comment]
Closed with: https://github.com/nyu-mll/jiant/pull/1122
