### ISSUE TITLE
WNLI not supported in tokenize_and_cache.py

### ISSUE THREAD

**Issue by jeswan** [jiant-dev/jiant#61]
**Describe the bug**
WNLI fails during tokenize and cache.

`Traceback (most recent call last):
  File "/home/js11133/jiant/jiant/proj/simple/tokenize_and_cache.py", line 184, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/home/js11133/jiant/jiant/proj/simple/tokenize_and_cache.py", line 153, in main
    evaluation_scheme = evaluate.get_evaluation_scheme_for_task(task)
  File "/home/js11133/jiant/jiant/tasks/evaluate/core.py", line 562, in get_evaluation_scheme_for_task
    raise KeyError(task)
KeyError: <jiant.tasks.lib.wnli.WnliTask object at 0x2b2a9cbe6cf8>`

**To Reproduce**
```
DATA_DIR=${WORKING_DIR}/data
MODELS_DIR=${WORKING_DIR}/models
CACHE_DIR=${WORKING_DIR}/cache

# ERROR with wnli, diagnostic, snli
#GLUE_TASKS=(cola mrpc qqp sst stsb mnli qnli rte)
GLUE_TASKS=(wnli)
MODEL_TYPE=bert-base-cased

mkdir -p ${DATA_DIR}
python ${TRANSFORMERS_PATH}/utils/download_glue_data.py \
    --data_dir ${DATA_DIR}/raw_glue_data

python ${JIANT_PATH}/scripts/preproc/export_glue_data.py \
    --input_base_path ${DATA_DIR}/raw_glue_data \
    --output_base_path ${DATA_DIR}/glue

python ${JIANT_PATH}/scripts/preproc/export_model.py \
    --model_type ${MODEL_TYPE} \
    --output_base_path ${MODELS_DIR}/${MODEL_TYPE}

for TASK_NAME in "${GLUE_TASKS[@]}"
do
	python ${JIANT_PATH}/proj/simple/tokenize_and_cache.py \
    		--task_config_path ${DATA_DIR}/glue/configs/${TASK_NAME}.json \
    		--model_type ${MODEL_TYPE} \
    		--model_tokenizer_path ${MODELS_DIR}/${MODEL_TYPE}/tokenizer \
    		--phases train,val,test \
    		--max_seq_length 256 \
    		--do_iter \
    		--smart_truncate \
    		--output_dir ${CACHE_DIR}/${MODEL_TYPE}/${TASK_NAME}
done
```

**Expected behavior**
Expect tokenize and cache similar to other tasks (ie: cola)

**Comment by jeswan** [comment]
Different error now:

```
Traceback (most recent call last):
  File "/home/js11133/jiant/jiant/proj/main/tokenize_and_cache.py", line 187, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/home/js11133/jiant/jiant/proj/main/tokenize_and_cache.py", line 140, in main
    examples=task.get_train_examples(),
  File "/home/js11133/jiant/jiant/tasks/lib/wnli.py", line 83, in get_train_examples
    return self._create_examples(lines=read_jsonl(self.train_path), set_type="train")
  File "/home/js11133/jiant/jiant/utils/python/io.py", line 27, in read_jsonl
    with open(path, "r") as f:
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by jeswan** [comment]
Fixed as of https://github.com/jiant-dev/jiant/pull/113
