### ISSUE TITLE
tokenize_and_cache.py fails for MultiRC

### ISSUE THREAD

**Issue by jeswan** [jiant-dev/jiant#76]
**Description**
tokenize_and_cache.py fails for MultiRC with the following error: 
```
Traceback (most recent call last):
  File "/home/js11133/jiant/jiant/proj/main/tokenize_and_cache.py", line 187, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/home/js11133/jiant/jiant/proj/main/tokenize_and_cache.py", line 140, in main
    examples=task.get_train_examples(),
  File "/home/js11133/jiant/jiant/tasks/lib/multirc.py", line 146, in get_train_examples
    return self._create_examples(lines=read_json_lines(self.train_path), set_type="train")
  File "/home/js11133/jiant/jiant/tasks/lib/multirc.py", line 160, in _create_examples
    soup = BeautifulSoup(line["passage"]["text"], "lxml")
  File "/home/js11133/.local/lib/python3.7/site-packages/bs4/__init__.py", line 245, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**To Reproduce**
```
python ${JIANT_PATH}/proj/main/tokenize_and_cache.py     --task_config_path ${DATA_DIR}/configs/${TASK_NAME}.json     --model_type ${MODEL_TYPE}     --model_tokenizer_path ${MODELS_DIR}/${MODEL_TYPE}/tokenizer     --phases train,val,test     --max_seq_length 256     --do_iter     --smart_truncate --output_dir ${CACHE_DIR}/${MODEL_TYPE}/${TASK_NAME}
```

**Additional context**
The following command does not generate the same error:
`python -c 'import requests ; from bs4 import BeautifulSoup ; r = requests.get("https://www.allrecipes.com/recipes/96/salad/") ; soup = BeautifulSoup(r.text, "lxml") '`

**Comment by zphang** [comment]
Is this for MNLI or MultiRC?

**Comment by jeswan** [comment]
@zphang MultiRC sorry...I have been looking at the tasks too long :)
