### ISSUE TITLE
tokenize_and_cache.py fails for WSC

### ISSUE THREAD

**Issue by jeswan** [jiant-dev/jiant#78]
**Describe the bug**
tokenize_and_cache.py fails for WSC with the following error:

```
Traceback (most recent call last):
  File "/home/js11133/jiant/jiant/proj/main/tokenize_and_cache.py", line 187, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/home/js11133/jiant/jiant/proj/main/tokenize_and_cache.py", line 178, in main
    args=args,
  File "/home/js11133/jiant/jiant/proj/main/tokenize_and_cache.py", line 47, in chunk_and_save
    phase=phase, examples=examples, feat_spec=feat_spec, tokenizer=tokenizer, args=args
  File "/home/js11133/jiant/jiant/proj/main/tokenize_and_cache.py", line 106, in iter_chunk_and_save
    recorder_callback=max_valid_length_recorder,
  File "/home/js11133/jiant/jiant/shared/caching.py", line 91, in iter_chunk_and_save
    for datum in data:
  File "/home/js11133/jiant/jiant/proj/main/preprocessing.py", line 139, in iter_chunk_convert_examples_to_dataset
    verbose=verbose,
  File "/home/js11133/jiant/jiant/proj/main/preprocessing.py", line 211, in iter_chunk_tokenize_and_featurize
    yield example.tokenize(tokenizer).featurize(tokenizer, feat_spec)
  File "/home/js11133/jiant/jiant/tasks/lib/wsc.py", line 49, in tokenize
    assert text[slice(*char_span1)].lower() == span1_text.lower()
```

**Additional Details**
Above assert occurs with example:

guid: test-80
assert details:
lhs: lev kamenev, stalin'
rhs: kamenev and zinoviev

**To Reproduce**
```
python ${JIANT_PATH}/proj/main/tokenize_and_cache.py     --task_config_path ${DATA_DIR}/configs/${TASK_NAME}.json     --model_type ${MODEL_TYPE}     --model_tokenizer_path ${MODELS_DIR}/${MODEL_TYPE}/tokenizer     --phases train,val,test     --max_seq_length 256     --do_iter     --smart_truncate     --output_dir ${CACHE_DIR}/${MODEL_TYPE}/${TASK_NAME} 
```

**Comment by zphang** [comment]
(Heads up, you can use triple back-ticks to format code blocks. This works well for output.)

**Comment by jeswan** [comment]
@zphang thanks!

**Comment by jeswan** [comment]
Failing examples:

```
span1_text: Kamenev and Zinoviev
span2_text: them
guid: test-80
1-lhs: "lev kamenev, stalin'"
1-rhs: 'kamenev and zinoviev'
2-lhs: 'them'
```

```
span1_text: Stalin and Kamenev
span2_text: them
guid: test-81
1-lhs: "kamenev, stalin's "
1-rhs: 'stalin and kamenev'
2-lhs: 'them'
2-rhs: 'them'
```

```
span1_text: Kamenev, Zinoviev, and Stalin
span2_text: them
guid: test-82
1-lhs: "kamenev, stalin's old pravda "
1-rhs: 'kamenev, zinoviev, and stalin'
2-lhs: 'them'
2-rhs: 'them'
```

```
span1_text: The traffic light.
span2_text: It
guid: test-117
1-lhs: 'the traffic light '
1-rhs: 'the traffic light.'
2-lhs: 'it'
2-rhs: 'it'
```

```
span1_text: The people in my reading group.
span2_text: they
guid: test-119
1-lhs: 'the people in my reading group '
1-rhs: 'the people in my reading group.'
2-lhs: 'they'
2-rhs: 'they'
```

and more....

**Comment by jeswan** [comment]
@zphang Would you agree that the first 3 examples are mistakes and can be excluded? Planning to strip the `.` from the following examples

**Comment by jeswan** [comment]
@pyeres These examples may be candidates for span alignment testing since they appear to be failing currently:

```
{"text": "Kotkin describes how Lev Kamenev, Stalin's old Pravda co-editor, and Grigory Zinoviev, who with Stalin and Kamenev had formed a ruling troika during Lenin's final illness, were dragged out of their prison cells in 1936 for a meeting with Stalin; he urged them to confess, for old times' sake.", "target": {"span1_text": "Kamenev and Zinoviev", "span1_index": 3, "span2_text": "them", "span2_index": 42}, "idx": 80}
```
```
{"text": "Kotkin describes how Lev Kamenev, Stalin's old Pravda co-editor, and Grigory Zinoviev, who with Stalin and Kamenev had formed a ruling troika during Lenin's final illness, were dragged out of their prison cells in 1936 for a meeting with Stalin; he urged them to confess, for old times' sake.", "target": {"span1_text": "Stalin and Kamenev", "span1_index": 4, "span2_text": "them", "span2_index": 42}, "idx": 81}
```
```
{"text": "Kotkin describes how Lev Kamenev, Stalin's old Pravda co-editor, and Grigory Zinoviev, who with Stalin and Kamenev had formed a ruling troika during Lenin's final illness, were dragged out of their prison cells in 1936 for a meeting with Stalin; he urged them to confess, for old times' sake.", "target": {"span1_text": "Kamenev, Zinoviev, and Stalin", "span1_index": 4, "span2_text": "them", "span2_index": 42}, "idx": 82}
```

**Comment by pyeres** [comment]
Hey @jeswan — looks like you're reporting an issue with the WSC data we're using (not the task implementation). Can you confirm?

**Comment by jeswan** [comment]
@pyeres I agree that test-80 and test-82 are issues with the data (seems like the current way to handle this is to specifically handle the exceptions in the task). test-81 appears to select the incorrect span (does span alignment help here?). test-117 and test-119 have spurious periods which we should handle gracefully.

**Comment by jeswan** [comment]
@W4ngatang Can you take a look at the failing examples and confirm that the WSC data is incorrect? @pyeres and I talked offline...test-81 has incorrect data (unlike what I stated previously). Furthermore, it is unclear why periods exist in the other examples (data does not look consistent).

**Comment by W4ngatang** [comment]
@pruksmhc can you comment? I didn't create the data, so I'm not sure what happened.

I'm not sure how to handle this. It looks like we'll need to modify these example, but it's a bit of a hassle since it's test data. What do you think @sleepinyourhat?

**Comment by jeswan** [comment]
@pruksmhc @sleepinyourhat @W4ngatang Any update on how we should handle this?

**Comment by W4ngatang** [comment]
Hi @jeswan , our plan is to leave those examples due to difficulties in modifying them b/c they are in the test set. In terms of handling them in jiant, I'm not sure if there's a clean solution for ya'll. Is it possible to have a strict mode and a non-strict mode where it warns rather than fails?

**Comment by jeswan** [comment]
@W4ngatang Thanks for the update. We'll work around the failing examples.
